lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem' # Chemin vers votre clé privée
    public_key: '%kernel.project_dir%/config/jwt/public.pem'  # Chemin vers votre clé publique
    pass_phrase: 'votre_passphrase' # La passphrase utilisée lors de la génération des clés
    token_ttl: 3600 # Durée de vie du token en secondes (1 heure)
